### ISSUE TITLE
Could use a function to deactivate doubletaptogo after it has been called

### ISSUE THREAD

**Issue by mkstix6** [zenopopovici/DoubleTapToGo#1]
I'd like to use this on a responsive site. On iPad landscape the desktop type nav shows and i need doubletaptogo. But on iPad portrait the mobile type drawer nav shows that has big buttons to open sub navs. So in the cases where someone goes from landscape to portrait I need to remove doubletaptogo from the elements i initialised it on.

Simply i'd like to be able to do something like:

On window size change
Check the size of the window width
If window width is large, activate doubletaptogo
If window width is small, deactivate doubletaptogo on the same items.

my code to initialise is:
    $( '.has-subnav' ).doubleTapToGo();

it would be nice to be able to do somthing like:
    $( '.has-subnav' ).doubleTapToGoOff();
or
    $( '.has-subnav' ).doubleTapToGo(false);

I could then use this function within my $(window).resize(.... logic.

**Comment by zenopopovici** [comment]
Let me see what I can do.

**Comment by zenopopovici** [comment]
Please check out Release 0.3. 
https://github.com/zenopopovici/DoubleTapToGo/releases/tag/v0.3

I had no way to test it out but it should work.

**Comment by mkstix6** [comment]
Thank you very much.

I'll test out the new code in the next couple of days.

**Comment by zenopopovici** [comment]
Any news?

**Comment by zenopopovici** [comment]
Assumed fixed.
