### ISSUE TITLE
Problems with submenu navigation on mobile.

### ISSUE THREAD

**Issue by AlexBazer** [zenopopovici/DoubleTapToGo#2]
Hello. You have nice piece of code in here. 
I used you function on my mobile version of http://beta.queen-time.ru/
But I encountered next problem, while navigation on submenus. 
When you tap "Здоровье и красота" and next tap on "Мода и стиль", last submenu would not be opend but instead you'll go to the "Дом и семья" page.

**Comment by zenopopovici** [comment]
The script works only for 2 level menus. You could try to re-initialize the script for the 3-rd parent. I simply don't have time to test this, but it should work.

**Comment by zenopopovici** [comment]
Sorry, this should work by changing the targeted selectors, no modifications are necessary.

E.g.:

```
<nav id="nav">
    <ul>
        <li>
            <a href="#">Parent Menu Item 1</a>
                <ul>
                    <li>
                        <a href="#">Child Menu Item 1</a>
                    </li>
                    <li>
                        <a href="#">Child Menu Item 2</a>
                    </li>
                    <li>
                        <a href="#">Child Menu Item 3</a>
                        <ul>
                          <li><a href="#">Child SubMenu Item 1</a></li>
                       </ul>
                    </li>
                </ul>
        </li>
        <li>
            <a href="#">Parent Menu Item 2</a>
        </li>
    </ul>
</nav>

$( 'ul > li:has(ul), #nav li ul li:has(ul),' ).doubleTapToGo();
```
